using Microsoft.VisualStudio.TestTools.UnitTesting;
using AnotherSpace;

namespace AnotherSpace.Tests
{
    [TestClass]
    class Class2Tests
    {
        [TestMethod]
        public void Test_Class2_FirstMethod_Method()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Test_Class2_SecondMethod_Method()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Test_Class2_ThirdMethod_Method()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Test_Class2_ThirdMethod2_Method()
        {
            Assert.Fail("autogenerated");
        }
    }
}