using Microsoft.VisualStudio.TestTools.UnitTesting;
using MyCode;

namespace MyCode.Tests
{
    [TestClass]
    public class MyClassTests
    {
        [TestMethod]
        public void Test_MyClass_FirstMethod_Method()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Test_MyClass_SecondMethod_Method()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Test_MyClass_ThirdMethod_Method()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Test_MyClass_ThirdMethod2_Method()
        {
            Assert.Fail("autogenerated");
        }
    }
}